name: english-study 
version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: English-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: English-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}