server:
  port: 8080

spring:
  application:
    name: english-study
  config:
    import: optional:file:.env[.properties]

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  # ===============================
  # Security (Resource Server - JWT)
  # ===============================
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}

  # ===============================
  # Docker Compose auto (Spring Boot hỗ trợ)
  # ===============================
  docker:
    compose:
      enabled: false
      lifecycle-management: start_only
  mongodb:
    uri: ${MONGO_URI:UnLoad}

# ===============================
# JWT custom config
# ===============================
jwt:
  secret: ${JWT_SECRET:my-secret-key-my-secret-key-my-secret-key}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}        # 1h (ms)
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}     # 7 ngày

# ===============================
# Logging
# ===============================
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# ===============================
# Actuator (nếu sau này bạn thêm)
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  default-role: ${DEFAULT_ROLE}
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:5173}

# ===============================
# Mongock
# ===============================
mongock:
  migration-scan-package:
    - com.english_study.config.dbmigrations
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}